version: '3.3'

services:

  db:
    image: mysql:8
    container_name: vacationplanner_mysql_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretRootPassword
      MYSQL_DATABASE: vacationplanner
      MYSQL_USER: vacationplannerUser
      MYSQL_PASSWORD: superSecretPassword
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    image: myapp
    container_name: vacationplanner_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vacationplanner?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: vacationplannerUser
      SPRING_DATASOURCE_PASSWORD: superSecretPassword
    networks:
      - backend

volumes:
  db_data:
networks:
  backend: